// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConversation(arg1) {
  return window['go']['main']['App']['AddConversation'](arg1);
}

export function AppenAgentMessageToFrontRole(arg1, arg2) {
  return window['go']['main']['App']['AppenAgentMessageToFrontRole'](arg1, arg2);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetMessagesByMessageID(arg1) {
  return window['go']['main']['App']['GetMessagesByMessageID'](arg1);
}

export function GetMessagesEvent(arg1) {
  return window['go']['main']['App']['GetMessagesEvent'](arg1);
}

export function GetReasoningMessage(arg1) {
  return window['go']['main']['App']['GetReasoningMessage'](arg1);
}

export function ListConversation() {
  return window['go']['main']['App']['ListConversation']();
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function UpdateConversationTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationTitle'](arg1, arg2);
}
