// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {proxy} from '../models';

export function AddConversation(arg1:string):Promise<string>;

export function AppenAgentMessageToFrontRole(arg1:context.Context,arg2:string,arg3:string):Promise<void>;

export function AppendMemoMarkdown(arg1:string):Promise<void>;

export function ComposeMemoWithLLM(arg1:string,arg2:string):Promise<string>;

export function DeleteConversation(arg1:string):Promise<void>;

export function GetConversation(arg1:string):Promise<void>;

export function GetLLMConfigEditorState():Promise<Record<string, any>>;

export function GetLLMConfigFormState():Promise<proxy.LLMConfigFormState>;

export function GetLLMConnectionStatus():Promise<proxy.LLMConnectionStatus>;

export function GetLLMResolvedConfigPath():Promise<string>;

export function GetLLMThinkingDisabled():Promise<boolean>;

export function GetLibraryWorkspaceRoot():Promise<string>;

export function GetLocalMemoryMessages(arg1:string):Promise<Array<Record<string, any>>>;

export function GetMemoCalendarDates():Promise<Array<string>>;

export function GetMemoContent():Promise<string>;

export function GetMemoFilePath():Promise<string>;

export function GetMemoReferencedMessageIDs():Promise<Array<string>>;

export function GetMessages(arg1:string):Promise<Array<Record<string, any>>>;

export function GetMessagesByMessageID(arg1:string):Promise<void>;

export function GetMessagesEvent(arg1:string):Promise<void>;

export function GetNovelResumeOutputDir(arg1:string,arg2:boolean):Promise<string>;

export function GetReasoningMessage(arg1:string):Promise<Array<Record<string, any>>>;

export function LibraryWorkspaceDelete(arg1:string,arg2:boolean):Promise<void>;

export function LibraryWorkspaceMkdir(arg1:string):Promise<void>;

export function LibraryWorkspaceRename(arg1:string,arg2:string):Promise<void>;

export function LibraryWorkspaceWriteFile(arg1:string,arg2:string):Promise<void>;

export function ListConversation():Promise<Array<Record<string, any>>>;

export function ListDocumentLibrary():Promise<Array<Record<string, any>>>;

export function ListLibraryWorkspaceDir(arg1:string):Promise<Record<string, any>>;

export function ReadDocumentForViewer(arg1:string):Promise<Record<string, any>>;

export function ResumeNovelLongform(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;

export function RevealDocumentInExplorer(arg1:string):Promise<void>;

export function SaveLLMConfigForm(arg1:proxy.LLMConfigRow,arg2:Array<proxy.LLMConfigRow>):Promise<string>;

export function SaveLLMConfigText(arg1:string):Promise<string>;

export function SaveMemoContent(arg1:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendUserDisplayOnly(arg1:string,arg2:string):Promise<void>;

export function SetLLMThinkingDisabled(arg1:boolean):Promise<void>;

export function StopChat(arg1:string):Promise<void>;

export function SwitchChat(arg1:string):Promise<void>;

export function UpdateConversationTitle(arg1:string,arg2:string):Promise<void>;
