// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConversation(arg1) {
  return window['go']['main']['App']['AddConversation'](arg1);
}

export function AppenAgentMessageToFrontRole(arg1, arg2, arg3) {
  return window['go']['main']['App']['AppenAgentMessageToFrontRole'](arg1, arg2, arg3);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetLLMConfigEditorState() {
  return window['go']['main']['App']['GetLLMConfigEditorState']();
}

export function GetLLMConnectionStatus() {
  return window['go']['main']['App']['GetLLMConnectionStatus']();
}

export function GetLLMResolvedConfigPath() {
  return window['go']['main']['App']['GetLLMResolvedConfigPath']();
}

export function GetLLMThinkingDisabled() {
  return window['go']['main']['App']['GetLLMThinkingDisabled']();
}

export function GetMemoCalendarDates() {
  return window['go']['main']['App']['GetMemoCalendarDates']();
}

export function GetMemoContent() {
  return window['go']['main']['App']['GetMemoContent']();
}

export function GetMemoFilePath() {
  return window['go']['main']['App']['GetMemoFilePath']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetMessagesByMessageID(arg1) {
  return window['go']['main']['App']['GetMessagesByMessageID'](arg1);
}

export function GetMessagesEvent(arg1) {
  return window['go']['main']['App']['GetMessagesEvent'](arg1);
}

export function GetReasoningMessage(arg1) {
  return window['go']['main']['App']['GetReasoningMessage'](arg1);
}

export function ListConversation() {
  return window['go']['main']['App']['ListConversation']();
}

export function SaveLLMConfigText(arg1) {
  return window['go']['main']['App']['SaveLLMConfigText'](arg1);
}

export function SaveMemoContent(arg1) {
  return window['go']['main']['App']['SaveMemoContent'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SetLLMThinkingDisabled(arg1) {
  return window['go']['main']['App']['SetLLMThinkingDisabled'](arg1);
}

export function StopChat(arg1) {
  return window['go']['main']['App']['StopChat'](arg1);
}

export function SwitchChat(arg1) {
  return window['go']['main']['App']['SwitchChat'](arg1);
}

export function UpdateConversationTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationTitle'](arg1, arg2);
}
