// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConversation(arg1:string):Promise<string>;

export function AppenAgentMessageToFrontRole(arg1:string,arg2:string):Promise<void>;

export function DeleteConversation(arg1:string):Promise<void>;

export function GetConversation(arg1:string):Promise<void>;

export function GetMessages(arg1:string):Promise<Array<Record<string, any>>>;

export function GetMessagesByMessageID(arg1:string):Promise<void>;

export function GetMessagesEvent(arg1:string):Promise<void>;

export function GetReasoningMessage(arg1:string):Promise<Array<Record<string, any>>>;

export function ListConversation():Promise<Array<Record<string, any>>>;

export function SendMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StopChat(arg1:string):Promise<void>;

export function UpdateConversationTitle(arg1:string,arg2:string):Promise<void>;
