// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConversation(arg1) {
  return window['go']['main']['App']['AddConversation'](arg1);
}

export function AppenAgentMessageToFrontRole(arg1, arg2, arg3) {
  return window['go']['main']['App']['AppenAgentMessageToFrontRole'](arg1, arg2, arg3);
}

export function AppendMemoMarkdown(arg1) {
  return window['go']['main']['App']['AppendMemoMarkdown'](arg1);
}

export function ComposeMemoWithLLM(arg1, arg2) {
  return window['go']['main']['App']['ComposeMemoWithLLM'](arg1, arg2);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetLLMConfigEditorState() {
  return window['go']['main']['App']['GetLLMConfigEditorState']();
}

export function GetLLMConfigFormState() {
  return window['go']['main']['App']['GetLLMConfigFormState']();
}

export function GetLLMConnectionStatus() {
  return window['go']['main']['App']['GetLLMConnectionStatus']();
}

export function GetLLMResolvedConfigPath() {
  return window['go']['main']['App']['GetLLMResolvedConfigPath']();
}

export function GetLLMThinkingDisabled() {
  return window['go']['main']['App']['GetLLMThinkingDisabled']();
}

export function GetLibraryWorkspaceRoot() {
  return window['go']['main']['App']['GetLibraryWorkspaceRoot']();
}

export function GetLocalMemoryMessages(arg1) {
  return window['go']['main']['App']['GetLocalMemoryMessages'](arg1);
}

export function GetMCPConfigFormState() {
  return window['go']['main']['App']['GetMCPConfigFormState']();
}

export function GetMemoCalendarDates() {
  return window['go']['main']['App']['GetMemoCalendarDates']();
}

export function GetMemoContent() {
  return window['go']['main']['App']['GetMemoContent']();
}

export function GetMemoFilePath() {
  return window['go']['main']['App']['GetMemoFilePath']();
}

export function GetMemoReferencedMessageIDs() {
  return window['go']['main']['App']['GetMemoReferencedMessageIDs']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetMessagesByMessageID(arg1) {
  return window['go']['main']['App']['GetMessagesByMessageID'](arg1);
}

export function GetMessagesEvent(arg1) {
  return window['go']['main']['App']['GetMessagesEvent'](arg1);
}

export function GetNovelResumeOutputDir(arg1, arg2) {
  return window['go']['main']['App']['GetNovelResumeOutputDir'](arg1, arg2);
}

export function GetReasoningMessage(arg1) {
  return window['go']['main']['App']['GetReasoningMessage'](arg1);
}

export function LibraryWorkspaceDelete(arg1, arg2) {
  return window['go']['main']['App']['LibraryWorkspaceDelete'](arg1, arg2);
}

export function LibraryWorkspaceMkdir(arg1) {
  return window['go']['main']['App']['LibraryWorkspaceMkdir'](arg1);
}

export function LibraryWorkspaceRename(arg1, arg2) {
  return window['go']['main']['App']['LibraryWorkspaceRename'](arg1, arg2);
}

export function LibraryWorkspaceWriteFile(arg1, arg2) {
  return window['go']['main']['App']['LibraryWorkspaceWriteFile'](arg1, arg2);
}

export function ListConversation() {
  return window['go']['main']['App']['ListConversation']();
}

export function ListDocumentLibrary() {
  return window['go']['main']['App']['ListDocumentLibrary']();
}

export function ListLibraryWorkspaceDir(arg1) {
  return window['go']['main']['App']['ListLibraryWorkspaceDir'](arg1);
}

export function ReadDocumentForViewer(arg1) {
  return window['go']['main']['App']['ReadDocumentForViewer'](arg1);
}

export function ResumeNovelLongform(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ResumeNovelLongform'](arg1, arg2, arg3, arg4, arg5);
}

export function RevealDocumentInExplorer(arg1) {
  return window['go']['main']['App']['RevealDocumentInExplorer'](arg1);
}

export function SaveLLMConfigForm(arg1, arg2) {
  return window['go']['main']['App']['SaveLLMConfigForm'](arg1, arg2);
}

export function SaveLLMConfigText(arg1) {
  return window['go']['main']['App']['SaveLLMConfigText'](arg1);
}

export function SaveMCPConfigForm(arg1) {
  return window['go']['main']['App']['SaveMCPConfigForm'](arg1);
}

export function SaveMemoContent(arg1) {
  return window['go']['main']['App']['SaveMemoContent'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SendUserDisplayOnly(arg1, arg2) {
  return window['go']['main']['App']['SendUserDisplayOnly'](arg1, arg2);
}

export function SetLLMThinkingDisabled(arg1) {
  return window['go']['main']['App']['SetLLMThinkingDisabled'](arg1);
}

export function StopChat(arg1) {
  return window['go']['main']['App']['StopChat'](arg1);
}

export function SwitchChat(arg1) {
  return window['go']['main']['App']['SwitchChat'](arg1);
}

export function UpdateConversationTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationTitle'](arg1, arg2);
}

export function ValidateMCPConfigRow(arg1) {
  return window['go']['main']['App']['ValidateMCPConfigRow'](arg1);
}
